t = input('Digite qualquer coisa: ')
print(type(t))
print('É um numero?', t.isnumeric())
print('É alfabetico?', t.isalpha())
print('Esta em letra maiuscula?', t.isupper())
print('Esta em letra minuscula?', t.islower())
